177,1
S,GetRealConjugate,"Returns a conjugate group in GL(N) that is of real type. (conjugated by [1,0,0,-1])",0,1,0,0,0,0,0,0,0,178,,178,-38,-38,-38,-38,-38
S,PSL2,"The projective special linear matrix group PSL(2,R)",0,1,0,0,0,0,0,0,0,-44,,GrpGL2Hat,-38,-38,-38,-38,-38
S,CongruenceSubgroup,"Given A = [n,m,p], this returns the congruence subgroup consisting of 2 by 2 matrices with integer coefficients [a,b,c,d] with a = d = 1 mod m, b = 0 mod p, and c = 0 mod n",0,1,0,0,0,0,0,0,0,82,,GrpGL2Hat,-38,-38,-38,-38,-38
S,CongruenceSubgroup,"Given N = [n,m,p], this returns the congruence subgroup consisting of 2 by 2 matrices with integer coefficients [a,b,c,d] with b = 0 mod p, and c = 0 mod n, and char(a) = 1 for char a Dirichlet character mod m",0,2,0,0,0,0,0,0,0,546,,0,0,82,,GrpGL2Hat,-38,-38,-38,-38,-38
S,CongruenceSubgroup,"The congruence subgroup Gamma_0(N), Gamma_1(N), Gamma(N), Gamma^1(N), or Gamma^0(N), when k = 0,1,2,3, or 4 respectively",0,2,0,0,0,0,0,0,0,148,,0,0,148,,GrpGL2Hat,-38,-38,-38,-38,-38
S,CongruenceSubgroup,The full projective congruence subgroup Gamma(N),0,1,0,0,0,0,0,0,0,148,,GrpGL2Hat,-38,-38,-38,-38,-38
S,Gamma0,creates the congruence subgroup Gamma_0(N),0,1,0,0,0,0,0,0,0,148,,GrpGL2Hat,-38,-38,-38,-38,-38
S,Gamma1,creates the congruence subgroup Gamma_1(N),0,1,0,0,0,0,0,0,0,148,,GrpGL2Hat,-38,-38,-38,-38,-38
S,GammaUpper0,creates the congruence subgroup Gamma^0(N),0,1,0,0,0,0,0,0,0,148,,GrpGL2Hat,-38,-38,-38,-38,-38
S,GammaUpper1,creates the congruence subgroup Gamma^1(N),0,1,0,0,0,0,0,0,0,148,,GrpGL2Hat,-38,-38,-38,-38,-38
S,GammaS,creates the congruence subgroup Gamma_s(N) which is split at all primes dividing N,0,1,0,0,0,0,0,0,0,148,,GrpGL2Hat,-38,-38,-38,-38,-38
S,GammaNS,"creates the congruence subgroup Gamma_ns(N), choosing alpha as the root of the polynomial f, which should be irreducible modulo each prime dividing N. Currently supports only the case where ZZ[alpha] is a maximal order, where alpha is a root of f",1,1,1,312,0,319,2,0,0,0,0,0,0,0,312,,0,0,148,,GrpGL2Hat,-38,-38,-38,-38,-38
S,GammaNS,"creates the congruence subgroup Gamma_ns(N), choosing u as the nonsquare such that N | a-d, N | b-uc",0,2,0,0,0,0,0,0,0,321,,0,0,148,,GrpGL2Hat,-38,-38,-38,-38,-38
S,GammaNS,creates the congruence subgroup Gamma_ns(N),0,1,0,0,0,0,0,0,0,148,,GrpGL2Hat,-38,-38,-38,-38,-38
S,GammaSplus,creates the congruence subgroup Gamma_s^plus(N),0,1,0,0,0,0,0,0,0,148,,GrpGL2Hat,-38,-38,-38,-38,-38
S,GammaNSplus,creates the congruence subgroup Gamma_ns^plus(N),0,2,0,0,0,0,0,0,0,321,,0,0,148,,GrpGL2Hat,-38,-38,-38,-38,-38
S,GammaNSplus,creates the congruence subgroup Gamma_ns^plus(N),0,1,0,0,0,0,0,0,0,148,,GrpGL2Hat,-38,-38,-38,-38,-38
S,GammaShimura,"creates the congruence subgroup Gamma(H,t), defined by Shimura. H is a subgroup of UnitGroup(ZZ / N ZZ), and t divides N. These are matrices such that modulo N they are upper triangular, the diagonal elements are in H, and the upper right element is a multiple of t",0,4,0,0,0,0,0,0,0,148,,0,0,107,,0,0,175,,0,0,107,,GrpGL2Hat,-38,-38,-38,-38,-38
S,/,Currently assumes the same level,0,2,0,0,0,0,0,0,0,GrpGL2Hat,,0,0,GrpGL2Hat,,GrpGL2Hat,-38,-38,-38,-38,-38
S,Transversal,Return coset representatives for HG,0,2,0,0,0,0,0,0,0,GrpGL2Hat,,0,0,GrpGL2Hat,,GrpGL2Hat,-38,-38,-38,-38,-38
S,Normalizer,The normalizer of a congruence subgroup in SL_2(R),0,1,0,0,0,0,0,0,0,GrpGL2Hat,,GrpGL2Hat,-38,-38,-38,-38,-38
S,MaximalNormalizingWithAbelianQuotient,,0,3,0,0,0,0,0,0,0,178,,0,0,178,,0,0,178,,178,-38,-38,-38,-38,-38
S,MaximalNormalizingWithAbelianQuotient,,0,1,0,0,0,0,0,0,0,GrpGL2Hat,,GrpGL2Hat,-38,-38,-38,-38,-38
S,Random,"returns a random element of the projective linear group G, m determines the size of the coefficients",0,2,0,0,0,0,0,0,0,148,,0,0,GrpGL2Hat,,GrpGL2HatElt,-38,-38,-38,-38,-38
S,Conjugate,"This function returns the conjugation of G by A, i.e. A^(-1)*G*A At the moment we only support the case where both input and output are subgroups of PSL2(Z)",0,2,0,0,0,0,0,0,0,180,,0,0,GrpGL2Hat,,GrpGL2Hat,-38,-38,-38,-38,-38
S,^,,0,2,0,0,0,0,0,0,0,180,,0,0,GrpGL2Hat,,GrpGL2Hat,-38,-38,-38,-38,-38
S,Intersection,returns the intersection of two congruence subgroups,0,2,0,0,0,0,0,0,0,GrpGL2Hat,,0,0,GrpGL2Hat,,GrpGL2Hat,-38,-38,-38,-38,-38
S,meet,returns the intersection of two congruence subgroups,0,2,0,0,0,0,0,0,0,GrpGL2Hat,,0,0,GrpGL2Hat,,GrpGL2Hat,-38,-38,-38,-38,-38
S,CalcLevel,calculates the level of a subgroup of PSL2,0,1,0,0,0,0,0,0,0,GrpGL2Hat,,148,-38,-38,-38,-38,-38
S,SubgroupFromGens,returns the subgroup of G generated by gens,0,4,0,0,0,0,0,0,0,36,,0,0,148,,0,0,82,,0,0,GrpGL2Hat,,GrpGL2Hat,-38,-38,-38,-38,-38
S,PSL2SubgroupFromGens,returns the subgroup of PSL2(R) generated by gens,0,4,0,0,0,0,0,0,0,36,,0,0,148,,0,0,-44,,0,0,82,,GrpGL2Hat,-38,-38,-38,-38,-38
S,FindLiftToSL2,finds a lift in SL2 for g,0,1,0,0,0,0,0,0,0,180,,GrpGL2HatElt,-38,-38,-38,-38,-38
S,FindLiftToM2Z,finds a lift in M2Z for g,1,0,1,177,0,320,1,0,0,0,0,0,0,0,177,,177,-38,-38,-38,-38,-38
S,SubgroupFromMod,returns the subgroup of G generated whose image is H0,0,4,0,0,0,0,0,0,0,36,,0,0,178,,0,0,148,,0,0,GrpGL2Hat,,GrpGL2Hat,-38,-38,-38,-38,-38
S,PSL2Subgroup,returns a subgroup of PSL2(Z) whose image is H (assumes -I in H),0,2,0,0,0,0,0,0,0,36,,0,0,178,,GrpGL2Hat,-38,-38,-38,-38,-38
S,PSL2Subgroup,returns a subgroup of PSL2(Z) whose image is H (assumes -I in H),0,1,0,0,0,0,0,0,0,178,,GrpGL2Hat,-38,-38,-38,-38,-38
S,PSL2Subgroup,returns a subgroup of PSL2(Z) whose image is H (assumes -I in H),0,2,0,0,0,0,0,0,0,298,,0,0,178,,GrpGL2Hat,-38,-38,-38,-38,-38
